server:
  port: 9342
spring:
  resources:
    static-locations: classpath:/templates/
  application:
    name: static-resources
eureka:
  instance:
    ip-address: true
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9020/eureka/

#ribbon.ReadTimeout=60000
#ribbon.ConnectTimeout=60000
#ribbon.MaxAutoRetries=0
#ribbon.MaxAutoRetriesNextServer=1
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

  #调试时开启