server:
  port: 9041
spring:
  application:
    name: shop-server
  mail:
    host: smtp.qq.com
    username: 942445346@qq.com
    password: efwlauvxmavobbda
    default-encoding: UTF-8
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123
    database: 10
    jedis:
      pool:
        max-active: 10
        max-wait: -1ms
    timeout: 5000ms
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: 123
     url: jdbc:mysql://localhost:3306/shops?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  rabbitmq:
    port: 5672
    virtual-host: /shop-service
    username: platform
    password: 123

eureka:
  instance:
    ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9020/eureka/
    healthcheck:
      enabled: true
